name: Cloud Build Deployment

on:
  push:
    branches:
      - main  # Mude para a ramificação desejada

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
        
      - name: Deploy to App Engine
        run: |
          gcloud app deploy app.yaml --quiet --promote
